[project]
name = "static-site-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "packaging>=25.0",
    "pp-ez>=0.2.0",
    "pprintpp>=0.4.0",
    "pygments>=2.19.1",
]
